FROM node:16.14.0-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
COPY yarn.lock ./

RUN yarn
COPY . ./

ARG REACT_APP_API_BASE_URL
ARG REACT_APP_CDN_URL
ARG REACT_APP_STOREFRONT_URL
ARG REACT_APP_TINY_MCE_API_KEY

RUN yarn build

# production environment
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]